# This is a basic workflow to help you get started with Actions

name: Matt Suntay       

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Force Clear Python Cache
        run: |
          sudo rm -rf /opt/hostedtoolcache/Python/

      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.10 
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run unit tests
        run: python -m pytest -v tests/
